/* Automatically generated by './build/dist.js' */

import clickoutside from './directives/clickoutside.js';
import copy from './directives/copy.js';
import debounce from './directives/debounce.js';
import draggable from './directives/draggable.js';
import focus from './directives/focus.js';

const directives = {
  clickoutside,
  copy,
  debounce,
  draggable,
  focus
}

const install = function(Vue, opts = {}) {
  Object.keys(directives).forEach(key => {
    Vue.directive(key, directives[key])
  })
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install
}
